trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: '20210818/gt-Geo-API'

stages:
- stage: Prepare
  displayName: Prepare artifacts
  jobs:
  - job: BuildApp
    displayName: Build Application
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        codeCoverageToolOption: 'JaCoCo'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false 
    - task: UniversalPackages@0
      inputs:
       command: 'download'
       downloadDirectory: '$(System.DefaultWorkingDirectory)'
       feedsToUse: 'internal'
       vstsFeed: '30b1d52d-57fc-4080-b11b-ccd6622fcccd'
       vstsFeedPackage: 'gt-geo'
       vstsPackageVersion: '1.*'
    - task: UniversalPackages@0
      inputs:
       command: 'publish'
       publishDirectory: '$(Build.ArtifactStagingDirectory)'
       feedsToUsePublish: 'internal'
       vstsFeedPublish: '30b1d52d-57fc-4080-b11b-ccd6622fcccd'
       vstsFeedPackagePublish: 'gt-geo'
       versionOption: 'patch'