trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: '20210818/gt-Geo-API'
  version: $[replace(replace(replace(utcNow(), '-', '.'), 'T', '.'), ':', '')]

stages:
- stage: Prepare
  displayName: Prepare artifacts
  jobs:
  - job: BuildApp
    displayName: Build Application
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        codeCoverageToolOption: 'JaCoCo'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact'
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/target'
        artifact: 'app'
    - task: UniversalPackages@0
      displayName: 'Publish Artifact to Azure Artifacts'
      inputs:
       command: 'publish'
       publishDirectory: '$(System.DefaultWorkingDirectory)/target'
       feedsToUsePublish: 'internal'
       vstsFeedPublish: '30b1d52d-57fc-4080-b11b-ccd6622fcccd'
       vstsFeedPackagePublish: 'gt-geo-1'
       versionOption: 'custom'
       versionPublish: '$(version)'
       packagePublishDescription: 'Publish Artifact to Azure Artifacts'
       verbosity: 'Error'
       publishedPackageVar: 'gt-geo-api'
       #$(Build.ArtifactStagingDirectory)
